services:
  db:
    image: postgres:18-alpine
    container_name: expenselite-db
    environment:
      POSTGRES_DB: expenselite
      POSTGRES_USER: expenselite_user
      POSTGRES_PASSWORD: expenselite123
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: expenselite-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expenselite
      SPRING_DATASOURCE_USERNAME: expenselite_user
      SPRING_DATASOURCE_PASSWORD: expenselite123
    depends_on:
      - db
