# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/expenselite
spring.datasource.username=expenselite_user
spring.datasource.password=expenselite123
spring.datasource.driver-class-name=org.postgresql.Driver
logging.config=classpath:logback-spring.xml
logging.pattern.console=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# App
server.port=8080
spring.application.name=expenselite-engine
